### ISSUE TITLE
Choose font

### ISSUE THREAD

**Issue by jarjan** [frontendkz/frontendkz.github.io#2]
http://www.google.com/fonts

**Comment by codev0** [comment]
Titles http://www.google.com/fonts/specimen/Ubuntu
Text http://www.google.com/fonts/specimen/Open+Sans

**Comment by drugoi** [comment]
Я за Roboto Condensed. Модно, молодежно :)

**Comment by manar-mk** [comment]
Roboto Condensed классный вариант) как у frontender.info )

**Comment by codev0** [comment]
Roboto Condensed для заголовков, нужно пару выбирать

**Comment by codev0** [comment]
можно like a medium

**Comment by codev0** [comment]
http://www.google.com/fonts/specimen/Ubuntu#pairings

**Comment by codev0** [comment]
http://www.latofonts.com/2014/02/27/lato-2-0-released/ как в slack

**Comment by manar-mk** [comment]
Lato + RobotoCondensed

**Comment by codev0** [comment]
https://www.dropbox.com/s/abso7skujbwfb40/fe.png
Ubuntu + Open Sans

**Comment by manar-mk** [comment]
Lato + RobotoCondensed
https://yadi.sk/i/9-yPrmaedrodi

**Comment by codev0** [comment]
@manar-mk да, Roboto Condensed хорошо смотрится, просто я не люблю Roboto потому что он везде, как Lobster, попса :)

**Comment by roose** [comment]
не не, нафик из фронтенд.инфо который, ужас :triumph:

**Comment by codev0** [comment]
@roose там его просто приготовили неправильно

**Comment by roose** [comment]
я за то что оставить текущий, гуглофонты отрубят не дай бог и ппц
