### ISSUE TITLE
Logo for community

### ISSUE THREAD

**Issue by talgautb** [frontendkz/frontendkz.github.io#23]
because we can :)

TODO:
- logo
- logo + text
- monochrome version

**Comment by jarjan** [comment]
Here is my proposal for logo:
![frontendkz logo 1](https://user-images.githubusercontent.com/836813/31013169-b3162e7a-a536-11e7-8951-c9abf384e8aa.png)
![frontendkz icon 1](https://user-images.githubusercontent.com/836813/31013408-d0c76a46-a537-11e7-8a59-959c6fa1ed40.png)


Colors are from our flag, and just some random ornament I found on internet. Font in `PT Sans` because it is used on [akorda.kz](http://akorda.kz) 😅 

I know, it is too much kazakh-y, but either way it looks more or less modern 🤷‍♂️

**Comment by codev0** [comment]
Ofc logo bellow is right
![](https://vuejs.org/images/logo.png)

**Comment by codev0** [comment]
![](https://i.imgur.com/hB72w68.png)
Another one, but logo above is better :D

**Comment by roose** [comment]
https://github.com/frontendkz/frontendkz.github.io/issues/23#issuecomment-333097041
Let's don't use the parts/colors of the state symbols.

**Comment by roose** [comment]
For example: https://github.com/shannonmoeller/front-end-logo

**Comment by jarjan** [comment]
Iteration of my previous version:
![2](https://user-images.githubusercontent.com/836813/31026807-901f5152-a569-11e7-8a69-4d6e2f88944d.png)

**Comment by jarjan** [comment]
Or maybe we can mimic JS logo?
![3](https://user-images.githubusercontent.com/836813/31026825-9ef98a58-a569-11e7-96bd-0b4da37ab19f.png)
![4](https://user-images.githubusercontent.com/836813/31026827-9f56ca88-a569-11e7-943d-f3d318fd2dff.png)

**Comment by zhiga90** [comment]
![frontend kz logo 2](https://user-images.githubusercontent.com/16041880/31029468-9b2b6eaa-a573-11e7-8bca-3387df9c0024.png)

**Comment by talgautb** [comment]
@jarjan maybe but it is often about *CITY*JS :) like AstanaJS, AlmatyJS and etc (https://github.com/voodootikigod/logo.js)

**Comment by roose** [comment]
![front-end-logo-bw-inverted](https://user-images.githubusercontent.com/277651/31045257-5a22eaf8-a601-11e7-9db1-e9a0d80808d5.png)
May be that? White on dark background and black on light?
![fedkz_2](https://user-images.githubusercontent.com/277651/31045326-182c4a20-a603-11e7-8386-155dc3dddb4d.png)

**Comment by roose** [comment]
Another variant:
![fedkz_3](https://user-images.githubusercontent.com/277651/31069990-8eb1fc7a-a780-11e7-8759-692a87e640ac.png)

**Comment by jarjan** [comment]
Curly brace as eagle 😆
![5](https://user-images.githubusercontent.com/836813/31073140-87fb1c70-a78c-11e7-9324-1197742ba12b.png)

**Comment by jarjan** [comment]
Or we can take flag of kazakh khanate get rid of everything:
![6](https://user-images.githubusercontent.com/836813/31073164-9a6e2938-a78c-11e7-88f1-75ac47522690.png)
And get our logo:
![7](https://user-images.githubusercontent.com/836813/31073165-9a6e9832-a78c-11e7-8424-8f368d2ce15c.png)
And that symbol looks like MacOS command key `⌘`

**Comment by roose** [comment]
![fedkz_5](https://user-images.githubusercontent.com/277651/31630026-2748af68-b2d7-11e7-9fa0-ef908607f632.png)
![fedkz_6](https://user-images.githubusercontent.com/277651/31630030-2a14bf0c-b2d7-11e7-99c2-a0b194cd7444.png)
![fedkz_test_2](https://user-images.githubusercontent.com/277651/31680059-ecf76ac0-b394-11e7-92cd-65b7d7180caa.png)

**Comment by zhiga90** [comment]
ассоциация немного с фейсбуком) Красиво конечно, но у вас сначала в логотипе было больше Front, теперь больше Kazakhstan))

**Comment by roose** [comment]
@zhiga90 ну дык, сами же казахизацию просили =)

**Comment by roose** [comment]
![fedkz_test_3](https://user-images.githubusercontent.com/277651/31680068-f853a708-b394-11e7-969a-81f5afbefd5a.png)
